using System;
using System.IO;
using System.Runtime.Versioning;
using System.Text.Json;
using CadHarness.Ir;
using CadHarness.SolidWorks;
using CadHarness.SolidWorks.Tests;
using CadHarness.State;
using SolidWorks.Interop.swconst;

[assembly: SupportedOSPlatform("windows")]

namespace CadHarness.State.Tests;

internal sealed class NativeReport
{
    public string Status { get; set; } = "BLOCKED";
    public string? FailureCode { get; set; }
    public string? Message { get; set; }
    public string? SolidWorksRevision { get; set; }
    public ResourceSnapshot? ResourceGuard { get; set; }
    public DocumentIdentity? DocumentIdentity { get; set; }
    public string? StatePath { get; set; }
    public RestoredManagedFeature? RestoredFeature { get; set; }
    public double? NativeParameterMm { get; set; }
    public bool StateLoadedFromDisk { get; set; }
    public bool OriginalActiveRestored { get; set; }
    public int PartsCreated { get; set; }
    public int PartsClosed { get; set; }
    public string? CleanupError { get; set; }
    public BudgetSnapshot? MilestoneBudget { get; set; }
}

internal static class Program
{
    [STAThread]
    private static int Main(string[] args)
    {
        if (args.Length is < 2 or > 3 || args[1] is not ("--pure" or "--live"))
        { Console.WriteLine("Usage: CadHarness.State.Tests <workspace> --pure|--live [part.prtdot]"); return 2; }
        return args[1] == "--pure" ? PureTests.Run(args[0]) : Live(args[0], args.Length == 3 ? args[2] : null);
    }

    private static int Live(string root, string? template)
    {
        var output = Path.Combine(root, "artifacts", "milestone3");
        Directory.CreateDirectory(output);
        NativeResourceGuard.TestTitlePrefix = "CADHarnessM3Test_";
        var report = new NativeReport();
        NativeTestBudget? budget = null;
        SolidWorksConnection? connection = null;
        TestPartScope? part = null;
        try
        {
            var fixture = File.ReadAllText(Path.Combine(root, "tests", "CadHarness.SolidWorks.Tests", "Fixtures", "extrude.json"));
            var parsed = new CadProgramJson().Parse(fixture);
            if (!parsed.IsValid) throw new TestFailure(parsed.Issues[0].Code, parsed.Issues[0].Message);
            var program = parsed.Program!;
            var preflight = MilestoneTwoProgram.Preflight(program);
            if (!preflight.IsValid) throw new TestFailure(preflight.FailureCode!, preflight.Message);
            budget = new(Path.Combine(output, "native-budget.json"), "Milestone 3");
            if (budget.Snapshot.CreationAttempts >= NativeTestBudget.MaximumParts)
                throw new TestFailure("ADDITIONAL_NATIVE_VALIDATION_RECOMMENDED", "M3 Part budget is exhausted; no Part was created.");
            Console.WriteLine("M3 connecting to SOLIDWORKS; no Part created yet.");
            connection = SolidWorksConnection.Connect();
            report.SolidWorksRevision = connection.Application.RevisionNumber();
            var partTemplate = connection.ResolvePartTemplate(template);
            report.ResourceGuard = NativeResourceGuard.Inspect(connection.Application, budget);
            var guard = report.ResourceGuard;
            Console.WriteLine(JsonSerializer.Serialize(guard));
            var resourceFailure = NativeResourceGuard.Evaluate(guard.Responding, guard.GdiCount, guard.OpenTestOwnedParts);
            if (resourceFailure is not null) throw new TestFailure(resourceFailure, "Native resource guard refused Part creation.");
            part = new(connection.Application, budget);
            var context = part.Create(connection, partTemplate);
            var execution = new CreateExtrudeHandler().Execute(context, program.Operations[0]);
            if (!execution.Succeeded) throw new TestFailure(execution.FailureCode!, execution.Message);
            DocumentIdentityAdapter.EnsurePersistentIds(context);
            var nativePath = Path.Combine(output, NativeResourceGuard.TestTitlePrefix + "plate_" + budget.Snapshot.CreationAttempts + ".sldprt");
            var errors = 0;
            var warnings = 0;
            try
            {
                if (!context.Document.Extension.SaveAs(nativePath, (int)swSaveAsVersion_e.swSaveAsCurrentVersion,
                        (int)swSaveAsOptions_e.swSaveAsOptions_Silent, null, ref errors, ref warnings) || errors != 0 || warnings != 0)
                    throw new TestFailure("STATE_COMMIT_FAILED", $"Native Part save failed: errors={errors}, warnings={warnings}.");
            }
            finally { part.RefreshOwnedTitle(); }
            if (!File.Exists(nativePath)) throw new TestFailure("STATE_COMMIT_FAILED", "Saved native Part file is missing.");
            var state = ExtrudeStateAdapter.Capture(context, program.Operations[0]);
            // Persist any native reference metadata generated by capture before
            // publishing the matching JSON snapshot.
            if (context.Document.GetSaveFlag())
            {
                errors = 0; warnings = 0;
                if (!context.Document.Save3((int)swSaveAsOptions_e.swSaveAsOptions_Silent, ref errors, ref warnings) || errors != 0 || warnings != 0)
                    throw new TestFailure("STATE_COMMIT_FAILED", "Native captured-reference metadata could not be saved.");
            }
            report.DocumentIdentity = state.Document;
            report.StatePath = Path.Combine(output, "cad-state.json");
            var store = new AtomicStateStore(report.StatePath);
            store.Commit(state);
            Console.WriteLine("Captured and atomically committed v0.2 CADState; loading a fresh copy from disk.");
            var loaded = store.Load();
            report.StateLoadedFromDisk = true;
            // A fresh context has no CreatedFeature handle. Restoration must
            // resolve the serialized native persistent reference, not reuse it.
            var restoredContext = new SolidWorksExecutionContext(context.Document);
            report.RestoredFeature = ExtrudeStateAdapter.Restore(restoredContext, loaded);
            report.NativeParameterMm = ExtrudeStateAdapter.ReadParameterMm(restoredContext, loaded, loaded.Parameters[0].SemanticId);
            if (Math.Abs(report.NativeParameterMm.Value - 10) > 1e-6 || report.RestoredFeature.ReferenceHealth != ReferenceHealth.Healthy)
                throw new TestFailure("PARAMETER_NOT_APPLIED", "Restored extrusion depth or reference health differs.");
            report.Status = "COMPLETE";
            report.Message = "One extrusion captured, persisted, restored by native persistent reference; native depth=10 mm.";
        }
        catch (StateException error) { report.FailureCode = error.Code; report.Message = error.Message; }
        catch (TestFailure error) { report.FailureCode = error.Code; report.Message = error.Message; }
        catch (Exception error) { report.FailureCode = "NATIVE_TEST_FAILED"; report.Message = error.GetType().Name + ": " + error.Message; }
        finally
        {
            if (part is not null)
            {
                part.Cleanup();
                report.PartsCreated = part.Created ? 1 : 0;
                report.PartsClosed = part.Closed ? 1 : 0;
                report.OriginalActiveRestored = part.OriginalActiveRestored;
                report.CleanupError = part.CleanupError;
                if (part.CleanupError is not null) { report.Status = "BLOCKED"; report.FailureCode = "TEST_CLEANUP_FAILED"; }
            }
            if (connection is not null)
            {
                try { connection.Dispose(); }
                catch (Exception error) { report.Status = "BLOCKED"; report.FailureCode = "TEST_CLEANUP_FAILED"; report.CleanupError = (report.CleanupError ?? "") + error.Message; }
            }
            if (budget is not null) { report.MilestoneBudget = budget.Snapshot; budget.Dispose(); }
            var json = JsonSerializer.Serialize(report, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(output, "native-result.json"), json + Environment.NewLine);
            Console.WriteLine(json);
        }
        return report.Status == "COMPLETE" ? 0 : 1;
    }
}
